---
- name: Deploy Node Exporter container
  docker_container:
    name: node-exporter
    image: prom/node-exporter:v1.8.2
    ports:
      - "9100:9100"
    networks:
      - name: monitoring
    labels:
      prometheus_job: "node-exporter"
    restart_policy: always

