---
- hosts: all
  become: true
  roles:
      - docker
      - docker_logging
      - common
      - prometheus
      - loki
      - node_exporter
      - alertmanager
      - cadvisor
      - grafana
